"""add generated sprint to projects

Revision ID: e8660c23c6d8
Revises: 8188176a01b7
Create Date: 2026-07-24 17:19:53.016505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8660c23c6d8'
down_revision: Union[str, Sequence[str], None] = '8188176a01b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('generated_sprint', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'generated_sprint')
    # ### end Alembic commands ###
